# SAM template for CodeBuild
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A simple AWS Lambda for retrieving information from the Users DynamnoDB table.
Resources:
  GetUserFx:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/get_user_fx-1.0-SNAPSHOT.jar
      Handler: com.revature.get_user.GetUserHandler
      Runtime: java8.al2
      Description: Java function
      MemorySize: 256
      Timeout: 30
      Tracing: Active
      Policies:
        - arn:aws:iam::011217676466:policy/dynamodb-readonly-users
